// Generated by gencpp from file tfg_valderico/nube.msg
// DO NOT EDIT!


#ifndef TFG_VALDERICO_MESSAGE_NUBE_H
#define TFG_VALDERICO_MESSAGE_NUBE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace tfg_valderico
{
template <class ContainerAllocator>
struct nube_
{
  typedef nube_<ContainerAllocator> Type;

  nube_()
    : nube_objetos()
    , xmin(0.0)
    , xmax(0.0)
    , ymin(0.0)
    , ymax(0.0)  {
    }
  nube_(const ContainerAllocator& _alloc)
    : nube_objetos(_alloc)
    , xmin(0.0)
    , xmax(0.0)
    , ymin(0.0)
    , ymax(0.0)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _nube_objetos_type;
  _nube_objetos_type nube_objetos;

   typedef double _xmin_type;
  _xmin_type xmin;

   typedef double _xmax_type;
  _xmax_type xmax;

   typedef double _ymin_type;
  _ymin_type ymin;

   typedef double _ymax_type;
  _ymax_type ymax;





  typedef boost::shared_ptr< ::tfg_valderico::nube_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tfg_valderico::nube_<ContainerAllocator> const> ConstPtr;

}; // struct nube_

typedef ::tfg_valderico::nube_<std::allocator<void> > nube;

typedef boost::shared_ptr< ::tfg_valderico::nube > nubePtr;
typedef boost::shared_ptr< ::tfg_valderico::nube const> nubeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tfg_valderico::nube_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tfg_valderico::nube_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tfg_valderico::nube_<ContainerAllocator1> & lhs, const ::tfg_valderico::nube_<ContainerAllocator2> & rhs)
{
  return lhs.nube_objetos == rhs.nube_objetos &&
    lhs.xmin == rhs.xmin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymin == rhs.ymin &&
    lhs.ymax == rhs.ymax;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tfg_valderico::nube_<ContainerAllocator1> & lhs, const ::tfg_valderico::nube_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tfg_valderico

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tfg_valderico::nube_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tfg_valderico::nube_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfg_valderico::nube_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfg_valderico::nube_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfg_valderico::nube_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfg_valderico::nube_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tfg_valderico::nube_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75228ef8c32422b6595ab2681e31aa11";
  }

  static const char* value(const ::tfg_valderico::nube_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75228ef8c32422b6ULL;
  static const uint64_t static_value2 = 0x595ab2681e31aa11ULL;
};

template<class ContainerAllocator>
struct DataType< ::tfg_valderico::nube_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tfg_valderico/nube";
  }

  static const char* value(const ::tfg_valderico::nube_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tfg_valderico::nube_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2 nube_objetos\n"
"float64 xmin\n"
"float64 xmax\n"
"float64 ymin \n"
"float64 ymax\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::tfg_valderico::nube_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tfg_valderico::nube_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nube_objetos);
      stream.next(m.xmin);
      stream.next(m.xmax);
      stream.next(m.ymin);
      stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nube_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tfg_valderico::nube_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tfg_valderico::nube_<ContainerAllocator>& v)
  {
    s << indent << "nube_objetos: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.nube_objetos);
    s << indent << "xmin: ";
    Printer<double>::stream(s, indent + "  ", v.xmin);
    s << indent << "xmax: ";
    Printer<double>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymin: ";
    Printer<double>::stream(s, indent + "  ", v.ymin);
    s << indent << "ymax: ";
    Printer<double>::stream(s, indent + "  ", v.ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TFG_VALDERICO_MESSAGE_NUBE_H
