// Generated by gencpp from file tfg_valderico/pointCoordinates.msg
// DO NOT EDIT!


#ifndef TFG_VALDERICO_MESSAGE_POINTCOORDINATES_H
#define TFG_VALDERICO_MESSAGE_POINTCOORDINATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tfg_valderico
{
template <class ContainerAllocator>
struct pointCoordinates_
{
  typedef pointCoordinates_<ContainerAllocator> Type;

  pointCoordinates_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  pointCoordinates_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::tfg_valderico::pointCoordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tfg_valderico::pointCoordinates_<ContainerAllocator> const> ConstPtr;

}; // struct pointCoordinates_

typedef ::tfg_valderico::pointCoordinates_<std::allocator<void> > pointCoordinates;

typedef boost::shared_ptr< ::tfg_valderico::pointCoordinates > pointCoordinatesPtr;
typedef boost::shared_ptr< ::tfg_valderico::pointCoordinates const> pointCoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tfg_valderico::pointCoordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tfg_valderico::pointCoordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tfg_valderico::pointCoordinates_<ContainerAllocator1> & lhs, const ::tfg_valderico::pointCoordinates_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tfg_valderico::pointCoordinates_<ContainerAllocator1> & lhs, const ::tfg_valderico::pointCoordinates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tfg_valderico

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tfg_valderico::pointCoordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tfg_valderico::pointCoordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfg_valderico::pointCoordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfg_valderico::pointCoordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfg_valderico::pointCoordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfg_valderico::pointCoordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tfg_valderico::pointCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::tfg_valderico::pointCoordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::tfg_valderico::pointCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tfg_valderico/pointCoordinates";
  }

  static const char* value(const ::tfg_valderico::pointCoordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tfg_valderico::pointCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tfg_valderico::pointCoordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tfg_valderico::pointCoordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pointCoordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tfg_valderico::pointCoordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tfg_valderico::pointCoordinates_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TFG_VALDERICO_MESSAGE_POINTCOORDINATES_H
