// Generated by gencpp from file tfg_valderico/vectorNubes.msg
// DO NOT EDIT!


#ifndef TFG_VALDERICO_MESSAGE_VECTORNUBES_H
#define TFG_VALDERICO_MESSAGE_VECTORNUBES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>
#include <tfg_valderico/coordObjetos.h>

namespace tfg_valderico
{
template <class ContainerAllocator>
struct vectorNubes_
{
  typedef vectorNubes_<ContainerAllocator> Type;

  vectorNubes_()
    : nube_objetos()
    , coord_objetos()
    , yaw(0.0)  {
    }
  vectorNubes_(const ContainerAllocator& _alloc)
    : nube_objetos(_alloc)
    , coord_objetos(_alloc)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _nube_objetos_type;
  _nube_objetos_type nube_objetos;

   typedef std::vector< ::tfg_valderico::coordObjetos_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tfg_valderico::coordObjetos_<ContainerAllocator> >::other >  _coord_objetos_type;
  _coord_objetos_type coord_objetos;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::tfg_valderico::vectorNubes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tfg_valderico::vectorNubes_<ContainerAllocator> const> ConstPtr;

}; // struct vectorNubes_

typedef ::tfg_valderico::vectorNubes_<std::allocator<void> > vectorNubes;

typedef boost::shared_ptr< ::tfg_valderico::vectorNubes > vectorNubesPtr;
typedef boost::shared_ptr< ::tfg_valderico::vectorNubes const> vectorNubesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tfg_valderico::vectorNubes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tfg_valderico::vectorNubes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tfg_valderico::vectorNubes_<ContainerAllocator1> & lhs, const ::tfg_valderico::vectorNubes_<ContainerAllocator2> & rhs)
{
  return lhs.nube_objetos == rhs.nube_objetos &&
    lhs.coord_objetos == rhs.coord_objetos &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tfg_valderico::vectorNubes_<ContainerAllocator1> & lhs, const ::tfg_valderico::vectorNubes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tfg_valderico

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tfg_valderico::vectorNubes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tfg_valderico::vectorNubes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfg_valderico::vectorNubes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfg_valderico::vectorNubes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfg_valderico::vectorNubes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfg_valderico::vectorNubes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tfg_valderico::vectorNubes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da8a0484e6abaf2fddc50498197a2b99";
  }

  static const char* value(const ::tfg_valderico::vectorNubes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda8a0484e6abaf2fULL;
  static const uint64_t static_value2 = 0xddc50498197a2b99ULL;
};

template<class ContainerAllocator>
struct DataType< ::tfg_valderico::vectorNubes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tfg_valderico/vectorNubes";
  }

  static const char* value(const ::tfg_valderico::vectorNubes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tfg_valderico::vectorNubes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2 nube_objetos\n"
"coordObjetos[] coord_objetos\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: tfg_valderico/coordObjetos\n"
"int64 xmin\n"
"int64 xmax\n"
"int64 ymin \n"
"int64 ymax\n"
"string clase\n"
;
  }

  static const char* value(const ::tfg_valderico::vectorNubes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tfg_valderico::vectorNubes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nube_objetos);
      stream.next(m.coord_objetos);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vectorNubes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tfg_valderico::vectorNubes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tfg_valderico::vectorNubes_<ContainerAllocator>& v)
  {
    s << indent << "nube_objetos: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.nube_objetos);
    s << indent << "coord_objetos[]" << std::endl;
    for (size_t i = 0; i < v.coord_objetos.size(); ++i)
    {
      s << indent << "  coord_objetos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tfg_valderico::coordObjetos_<ContainerAllocator> >::stream(s, indent + "    ", v.coord_objetos[i]);
    }
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TFG_VALDERICO_MESSAGE_VECTORNUBES_H
